apiVersion: v2
name: objecttypes
description: A Helm chart for Objecttypes API

type: application
version: 0.2.0
appVersion: "1.16.0"

dependencies:
  - name: postgresql
    version: ~10.2.0
    repository: https://charts.bitnami.com/bitnami
    tags:
      - postgresql
  - name: redis
    version: ~13.0.0
    repository: https://charts.bitnami.com/bitnami
    tags:
      - redis
